Fixing cart rule error with 1 available cart rule quantity
Invertus-mollie/PrestaShop pull request #188
Opened 2020-12-17 10:46 UTC by tomjas1997

2020-12-17 11:38 UTC, tomas862 commented on src/Handler/CartRule/CartRuleHandler.php
> +
try to loose the habit of directly using objects- use repositories.

create OrderRepository with method findOneByCartId

to fetch this order

2020-12-17 11:39 UTC, tomas862 commented on src/Handler/CartRule/CartRuleHandler.php
> +			$orderCartRule = $this->orderCartRuleRepository->getOrderCartRule($order, $cartRule);
instead of passing $cartRule pass only id

2020-12-17 11:39 UTC, tomas862 commented on src/Handler/CartRule/CartRuleHandler.php
> +		$orderId = Order::getOrderByCartId($cart->id); /* @phpstan-ignore-line */
duplicate code fragment, also why phpstan is ignored here ?

2020-12-17 11:39 UTC, tomas862 commented on src/Handler/CartRule/CartRuleHandler.php
> +			$cartRule = new CartRule($cartRuleContent['id_cart_rule']);
duplicate code fragment, almost

2020-12-17 11:41 UTC, tomas862 commented on src/Repository/OrderCartRuleRepository.php
> +final class OrderCartRuleRepository
extend AbstractRepository, you will find some methods useful I assume.

2020-12-17 11:42 UTC, tomas862 commented on src/Repository/OrderCartRuleRepository.php
> +	public function getOrderCartRule($order, CartRule $cartRule)
if you extend abstract Repo you could achieve same by using `findOneBy` method. Forgot if its implemented, if not implement it :)

2020-12-17 11:44 UTC, tomas862 commented on src/Repository/PendingOrderCartRuleRepository.php
> +	public function getPendingOrderCartRule($order, CartRule $cartRule)
same here, try to extend Abstract repo, you might find that some methods are redundant

2020-12-17 11:45 UTC, tomas862 requested changes
not a single unit test ? :thinking:

2020-12-17 13:13 UTC, tomjas1997 commented
> not a single unit test ?

Almost all changes are interacting with database, this calls for system tests

2020-12-18 11:40 UTC, tomas862 commented on src/Handler/CartRule/CartRuleQuantityResetHandler.php
> +		/** @var Order $order */
typehint should be Order|null since you might not find Order as well

2020-12-18 11:41 UTC, tomas862 commented on src/Repository/CartRuleRepository.php
> +}
so neat looking service :eyes:

2020-12-18 11:48 UTC, tomas862 commented on src/Service/OrderCartAssociationService.php
> +		$newCartId = $this->cartDuplication->restoreCart($order->id_cart, Config::RESTORE_CART_BACKTRACE_MEMORIZATION_SERVICE);
first of all I would prefer **enum** usage in PHP https://stackoverflow.com/questions/254514/php-and-enumerations . Something like this or this package https://packagist.org/packages/myclabs/php-enum

what it gives is type strictness so we cant pass any random string - we would receive error. 

Also what else it gives is that you can warp related configuration and document it as well.

2020-12-18 11:49 UTC, tomas862 commented on src/Service/OrderCartAssociationService.php
> +		$newCartId = $this->cartDuplication->restoreCart($order->id_cart, Config::RESTORE_CART_BACKTRACE_MEMORIZATION_SERVICE);
This is aswell now optional suggestion, but if you have a bit spare time I would dive into this implementation and would deprecate remaining configs

2020-12-18 11:50 UTC, tomas862 approved these changes
overall looks very good! Im approving just that I left 1 small fix and well one suggestion to use if you have time to implement :)

2020-12-18 11:56 UTC, merged